 ;=============================================================================;
 ; Все замечания и пожелания прошу направлять по адресу:   vertexland@narod.ru ;
 ; Страничка где вы можете скачать свежую версию:          vertexland.narod.ru ;
 ;                                                                             ;
 ;                            Created (c) 2004-2005. keYMax (Пономарев Михаил) ;
 ;=============================================================================;

 ; DirectSound api calls (ASCII)

   import  dsound,   DirectSoundCreate,             'DirectSoundCreate',             \
                     DirectSoundEnumerateA,         'DirectSoundEnumerateA',         \
                     DirectSoundEnumerateW,         'DirectSoundEnumerateW',         \
                     DirectSoundCaptureCreate,      'DirectSoundCaptureCreate',      \
                     DirectSoundCaptureEnumerateA,  'DirectSoundCaptureEnumerateA',  \
                     DirectSoundCaptureEnumerateW,  'DirectSoundCaptureEnumerateW',  \
                     DirectSoundCreate8,            'DirectSoundCreate8',            \
                     DirectSoundCaptureCreate8,     'DirectSoundCaptureCreate8',     \
                     DirectSoundFullDuplexCreate,   'DirectSoundFullDuplexCreate',   \
                     DirectSoundFullDuplexCreate8,  'DirectSoundFullDuplexCreate8',  \
                     GetDeviceID,                   'GetDeviceID'


